--- 
:accounts: 
  :default: 
    :name: Steven Hum
    :email: sdothum@gmail.com
    :alternates: []

    :sendmail: ""
    :signature: /home/shum/.signature
    :gpgkey: ""
# :editor: vim -g -f -c 'set filetype=mail'
# :editor: gvim -f -c 'set filetype=mail'
:editor: dcompose
:thread_by_subject: false
:edit_signature: false
:ask_for_from: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: true
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ""
:sent_source: sup://sent
:archive_sent: true
:poll_interval: 60
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
# :sync_back_to_maildir: true
:index: xapian
